name: debug-packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Choose a tag for the image'
        required: false
        default: 'dev'
        type: choice
        options:
          - latest
          - dev
          - nightly

env:
  REGISTRY_SERVER_ADDRESS: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Determine tags
      id: tag-determination
      run: |
        tags="latest"
        ref=${{ github.ref }}
        if [ "${ref}" == "refs/heads/master" ]; then
          tags="master $tags"
        elif [[ "${ref}" =~ ^refs\/tags\/v.*$ ]]; then
          tags="${{ replace(ref, 'refs/tags/', '') }} $tags"
        elif [[ -n "${{ github.event.inputs.tag }}" ]]; then
          tags="${{ github.event.inputs.tag }}"
        fi
        echo "::set-output name=tags::$tags"
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ./docker/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.REGISTRY_SERVER_ADDRESS }}:${{ steps.tag-determination.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}